export const categoriesConstants = {
    GET_CATEGORIES_REQUEST  : "GET_CATEGORIES_REQUEST",
    GET_CATEGORIES_SUCCESS : "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILURE : "GET_CATEGORIES_FAILURE",
}

export const sideGridConstants = {
    GET_SIDEGRIDS_REQUEST  : "GET_SIDEGRIDS_REQUEST",
    GET_SIDEGRIDS_SUCCESS : "GET_SIDEGRIDS_SUCCESS",
    GET_SIDEGRIDS_FAILURE : "GET_SIDEGRIDS_FAILURE",
}

export const articleConstants = {
    GET_ARTICLE_REQUEST  : "GET_ARTICLE_REQUEST",
    GET_ARTICLE_SUCCESS : "GET_ARTICLE_SUCCESS",
    GET_ARTICLE_FAILURE : "GET_ARTICLE_FAILURE",
}