export const categoriesConstants = {
    GET_CATEGORIES_REQUEST  : "GET_CATEGORIES_REQUEST",
    GET_CATEGORIES_SUCCESS : "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILURE : "GET_CATEGORIES_FAILURE",
}

export const sideGridConstants = {
    GET_SIDEGRIDS_REQUEST  : "GET_SIDEGRIDS_REQUEST",
    GET_SIDEGRIDS_SUCCESS : "GET_SIDEGRIDS_SUCCESS",
    GET_SIDEGRIDS_FAILURE : "GET_SIDEGRIDS_FAILURE",
}

export const articleConstants = {
    GET_ARTICLE_REQUEST  : "GET_ARTICLE_REQUEST",
    GET_ARTICLE_SUCCESS : "GET_ARTICLE_SUCCESS",
    GET_ARTICLE_FAILURE : "GET_ARTICLE_FAILURE",
}

export const bannerConstants = {
    GET_BANNER_REQUEST  : "GET_BANNER_REQUEST",
    GET_BANNER_SUCCESS : "GET_BANNER_SUCCESS",
    GET_BANNER_FAILURE : "GET_BANNER_FAILURE",
}

export const featuredConstants = {
    GET_FEATURED_REQUEST  : "GET_FEATURED_REQUEST",
    GET_FEATURED_SUCCESS : "GET_FEATURED_SUCCESS",
    GET_FEATURED_FAILURE : "GET_FEATURED_FAILURE",
}

export const articlesConstants = {
    GET_ARTICLES_REQUEST  : "GET_ARTICLES_REQUEST",
    GET_ARTICLES_SUCCESS : "GET_ARTICLES_SUCCESS",
    GET_ARTICLES_FAILURE : "GET_ARTICLES_FAILURE",
    CHANGE_SEARCH_TERM: "CHANGE_SEARCH_TERM",
    RESET_ARTICLES: "RESET_ARTICLES"
}